apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appId }}-service
spec:
  selector:
    app: {{ .Values.appId }}-app 
  ports:
    - name: http
      protocol: TCP      
      port: {{ .Values.port }}
      targetPort: 80
    - name: metrics
      protocol: TCP     
      port: 9464
      targetPort: 9464
