apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://user:bitnami@rabbitmq:5672"
  - name: protocol
    value: amqp  
  - name: hostname
    value: pubsubqueue 
  - name: username
    value: user
  - name: password
    value: bitnami
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel